#!/usr/bin/env python3
import pdfplumber
import csv
import re
import sys
from pathlib import Path
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter

FIELDS = [
    'page', 'flight_number', 'takeoff_datetime', 'title',
    'address', 'takeoff_lat', 'takeoff_lon', 'takeoff_asl_ft', 'takeoff_dms',
    'landing_time', 'pilot', 'pilot_organization', 'license_number',
    'flight_app', 'drone_name', 'drone_serial', 'drone_registration', 'drone_type',
    'air_ground_time', 'air_ground_seconds', 'tags', 'case_cad_number',
    'weather_summary', 'ground_temp_f', 'ground_visibility_miles',
    'ground_wind_speed', 'ground_wind_dir', 'cloud_cover', 'humidity',
    'dew_point_f', 'pressure', 'rain_rate', 'rain_chance',
    'sunrise', 'sunset', 'moon_phase', 'moon_visibility',
    'notes',
]

# All known labeled fields — used as lookahead stops to bound each value capture
_LABELS = [
    r'Pilot-in-Command', r'Takeoff Lat/Long', r'Flight App',
    r'Above Sea Level \(Feet\)', r'Takeoff Degrees/Minutes/Seconds',
    r'Landing Time', r'Drone Serial Number', r'Drone Registration Number',
    r'Drone Name', r'Drone Type', r'Pilot Organization', r'License Number',
    r'Air\+Ground Time', r'Air\+Ground Seconds', r'Air\+Ground 0\.1hour',
    r'Tags', r'Ground Weather Summary', r'Weather Summary',
    r'Ground Temp \(f\)', r'Ground Visibility \(Miles\)', r'Ground Wind Speed',
    r'Ground Wind Dir', r'Cloud Cover', r'Humidity', r'Dew Point \(f\)',
    r'Pressure', r'Rain Rate', r'Rain Chance', r'Sunrise', r'Sunset',
    r'Moon Phase', r'Moon Visibility', r'Case or CAD Number',
]
_STOP = r'(?=' + '|'.join(f'{l}:' for l in _LABELS) + r'|\Z)'

# Blue header fill color (RGB 0-1): the light-blue flight header background
_BLUE = (0.807843137, 0.882352941, 0.960784313)
_BLUE_TOL = 0.01


def _get(pattern, text, group=1, flags=re.DOTALL):
    m = re.search(pattern, text, flags)
    return m.group(group).strip() if m else ''


def _field(label, text):
    """Extract value for a labeled field, stopping at the next known label."""
    m = re.search(label + r':\s*(.+?)' + _STOP, text, re.DOTALL)
    return m.group(1).strip().replace('\n', ' ') if m else ''


def _is_blue(color):
    if not isinstance(color, tuple) or len(color) != 3:
        return False
    return all(abs(color[i] - _BLUE[i]) < _BLUE_TOL for i in range(3))


# ---------------------------------------------------------------------------
# Page extraction
# ---------------------------------------------------------------------------

def extract_pages(pdf_path):
    """Return (pages, total_pages, page_words, blue_rects).

    pages      : list of (page_num, text)
    page_words : dict  page_num -> list of word dicts (text, top, x0, x1)
    blue_rects : dict  page_num -> sorted list of (top, bottom) for blue header rects
    """
    pages = []
    page_words = {}
    blue_rects = {}

    with pdfplumber.open(pdf_path) as pdf:
        total = len(pdf.pages)
        for pg_num, page in enumerate(pdf.pages):
            text = page.extract_text() or ''
            text = re.sub(r'\nGenerated by Airdata UAV.*$', '', text, flags=re.MULTILINE)
            pages.append((pg_num, text))

            page_words[pg_num] = page.extract_words()

            rects = sorted(
                (r['top'], r['bottom'])
                for r in page.rects
                if _is_blue(r.get('non_stroking_color'))
            )
            blue_rects[pg_num] = rects

    return pages, total, page_words, blue_rects


# ---------------------------------------------------------------------------
# Metadata
# ---------------------------------------------------------------------------

def parse_metadata(pages, pdf_path):
    meta = {}
    first_text = pages[0][1] if pages else ''

    m = re.search(r'^(.+?)\s+Reported flights:\s*(\d+)', first_text, re.MULTILINE)
    if m:
        meta['agency'] = m.group(1).strip()
        meta['total_flights'] = m.group(2)

    # Report number: "Flight Report #102" or "PDR S019856-021826"
    m = (re.search(r'Flight Report #(\d+)', first_text) or
         re.search(r'\b(PDR\s+\S+)', first_text))
    if m:
        meta['report_number'] = m.group(1)

    # Period: "Jan 1st, 2025 to Dec 31st, 2025" or abbreviated "Jan 2025 to Dec 2025"
    m = (re.search(r'([\w]+ \d+\w+, \d{4}) to ([\w]+ \d+\w+, \d{4})', first_text) or
         re.search(r'(\w+ \d{4}) to (\w+ \d{4})', first_text))
    if m:
        meta['period_start'] = m.group(1)
        meta['period_end'] = m.group(2)

    with pdfplumber.open(pdf_path) as pdf:
        last_text = pdf.pages[-1].extract_text() or ''
    m = re.search(r'Created on (.+?)$', last_text, re.MULTILINE)
    if m:
        meta['created'] = m.group(1).strip()

    m = re.search(r'Generated by (.+?) Page', last_text)
    if m:
        meta['generated_by'] = m.group(1).strip()

    return meta


# ---------------------------------------------------------------------------
# Coordinate-based title / address classification
# ---------------------------------------------------------------------------

def _classify_header(flight_num, inline_title, page_num, page_words, blue_rects):
    """Use word coordinates and blue-rect boundaries to split title from address.

    Returns (title, address).  Falls back to (inline_title, '') if anchors
    cannot be found.
    """
    words = page_words.get(page_num, [])
    rects = blue_rects.get(page_num, [])

    # Find the '#N' word on this page to anchor the flight's position.
    target = f'#{flight_num}'
    fn_candidates = [w for w in words if w['text'] == target]
    if not fn_candidates:
        return inline_title, ''

    # There should be exactly one; take the first.
    fn_word = fn_candidates[0]
    fn_top = fn_word['top']

    # Find the blue header rect whose range contains the flight-number word.
    # Multiple overlapping sub-rects may exist; use the largest (max bottom).
    containing = [b for (t, b) in rects if t <= fn_top <= b]
    if not containing:
        return inline_title, ''
    header_bottom = max(containing)

    # Detailed format has Pilot-in-Command in the white section right column.
    # Summary format (e.g. Marysville) has no labeled fields — single-column layout.
    pic_words = [w for w in words
                 if w['text'].startswith('Pilot-in-Command') and w['top'] > fn_top]

    title_words = []
    addr_words  = []

    if pic_words:
        # Detailed format: use Pilot-in-Command as column/row boundary.
        pic_word = min(pic_words, key=lambda w: w['top'])
        pic_top = pic_word['top']
        pic_x0  = pic_word['x0']

        takeoff_words = [w for w in words if w['text'] == 'Takeoff' and w['top'] > pic_top]
        takeoff_top = min((w['top'] for w in takeoff_words), default=pic_top + 999)

        for w in words:
            top = w['top']
            if top <= fn_top or top > takeoff_top + 2:
                continue
            if top < header_bottom - 1:
                title_words.append(w)
            elif top <= pic_top + 2 and w['x0'] < pic_x0:
                addr_words.append(w)
    else:
        # Summary format: title in blue header, address in white section before next flight.
        next_tops = [t for (t, b) in rects if t > header_bottom]
        next_flight_top = min(next_tops, default=fn_top + 9999)

        for w in sorted(words, key=lambda w: (round(w['top']), w['x0'])):
            top = w['top']
            if top <= fn_top:
                continue
            if top >= next_flight_top or w['text'].startswith(('Notes', 'Generated')):
                break
            if top < header_bottom - 1:
                title_words.append(w)
            else:
                addr_words.append(w)

    def reconstruct(wlist):
        # Sort top-to-bottom, left-to-right; insert spaces between words.
        wlist = sorted(wlist, key=lambda w: (round(w['top']), w['x0']))
        if not wlist:
            return ''
        parts = []
        prev = wlist[0]
        parts.append(prev['text'])
        for w in wlist[1:]:
            # New line or large horizontal gap → space separator
            parts.append(' ')
            parts.append(w['text'])
        return ''.join(parts).strip()

    header_extra = reconstruct(title_words)
    title = (inline_title + (' ' + header_extra if header_extra else '')).strip()
    address = re.sub(r',?\s*USA\s*$', ', USA', reconstruct(addr_words)).strip()
    # If address resolved to only a label fragment (e.g. "Takeoff Lat/Long:"), clear it.
    if re.search(r':\s*$', address):
        address = ''
    return title, address


# ---------------------------------------------------------------------------
# Flight parsing
# ---------------------------------------------------------------------------

def parse_flight_block(block, page_num, page_words, blue_rects):
    f = {'page': page_num + 1}

    # --- Flight header: datetime and flight number ---
    # Patterns: "Flight\nDate\n#N", "Flight Date\n#N", or "Date\nFlight\n#N"
    m = (re.match(r'Flight(?:\n| +)(.+?)\n#(\d+)([ \t]*(.+?))?\n', block) or
         re.match(r'([A-Z][a-z]+.+?)\nFlight\n#(\d+)([ \t]*(.+?))?\n', block))
    if m:
        f['takeoff_datetime'] = m.group(1).strip()
        f['flight_number']    = m.group(2)
        inline_title          = m.group(4).strip() if m.group(4) else ''

        title, address = _classify_header(
            f['flight_number'], inline_title, page_num, page_words, blue_rects
        )
        f['title']   = title
        f['address'] = address

    # --- All labeled fields ---
    f['pilot']                   = _field(r'Pilot-in-Command', block)
    f['pilot_organization']      = _field(r'Pilot Organization', block)
    f['license_number']          = _field(r'License Number', block)
    f['flight_app']              = _field(r'Flight App', block)
    f['takeoff_asl_ft']          = _field(r'Above Sea Level \(Feet\)', block)
    f['takeoff_dms']             = _field(r'Takeoff Degrees/Minutes/Seconds', block)
    f['landing_time']            = _field(r'Landing Time', block)
    f['drone_name']              = _field(r'Drone Name', block)
    f['drone_serial']            = _field(r'Drone Serial Number', block)
    f['drone_registration']      = _field(r'Drone Registration Number', block)
    f['drone_type']              = _field(r'Drone Type', block)
    f['air_ground_time']         = _field(r'Air\+Ground Time', block)
    f['air_ground_seconds']      = _field(r'Air\+Ground Seconds', block)
    f['tags']                    = _field(r'Tags', block)
    f['case_cad_number']         = _field(r'Case or CAD Number', block)

    ws = _field(r'Ground Weather Summary', block) or _field(r'Weather Summary', block)
    f['weather_summary']         = ws
    f['ground_temp_f']           = _field(r'Ground Temp \(f\)', block)
    f['ground_visibility_miles'] = _field(r'Ground Visibility \(Miles\)', block)
    f['ground_wind_speed']       = _field(r'Ground Wind Speed', block)
    f['ground_wind_dir']         = _field(r'Ground Wind Dir', block)
    f['cloud_cover']             = _field(r'Cloud Cover', block)
    f['humidity']                = _field(r'Humidity', block)
    f['dew_point_f']             = _field(r'Dew Point \(f\)', block)
    f['pressure']                = _field(r'Pressure', block)
    f['rain_rate']               = _field(r'Rain Rate', block)
    f['rain_chance']             = _field(r'Rain Chance', block)
    f['sunrise']                 = _field(r'Sunrise', block)
    f['sunset']                  = _field(r'Sunset', block)
    f['moon_phase']              = _field(r'Moon Phase', block)
    f['moon_visibility']         = _field(r'Moon Visibility', block)

    m = re.search(r'Takeoff Lat/Long:\s*([\d.-]+),\s*([\d.-]+)', block)
    if m:
        f['takeoff_lat'] = m.group(1)
        f['takeoff_lon'] = m.group(2)

    f['notes'] = _field(r'Notes', block)

    return f


_MONTHS = r'(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)'
_FLIGHT_SPLIT = re.compile(
    r'(?m)(?=^(?:'
    r'Flight\n' + _MONTHS + r'|'       # Format A: Flight\n<Month>...
    r'Flight ' + _MONTHS + r' \d|'     # Format B: Flight <Month> <day>
    + _MONTHS + r' \d+[a-z]+, \d{4} \d+:\d+[AP]M\nFlight\n#'  # Format C: <date>\nFlight\n#
    r'))'
)


def parse_flights(pages, page_words, blue_rects):
    flights = []
    for pg_num, text in pages:
        blocks = _FLIGHT_SPLIT.split(text)
        for block in blocks:
            block = block.strip()
            f = parse_flight_block(block, pg_num, page_words, blue_rects)
            if f.get('flight_number'):
                flights.append(f)
    return flights


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

def clean(v):
    return re.sub(r'[\r\n]+', ' ', str(v)).strip()


def write_csv(out_path, metadata, flights, include_metadata):
    with open(out_path, 'w', newline='', encoding='utf-8-sig') as fh:
        if include_metadata:
            meta_lines = [
                f"# {metadata.get('generated_by', 'Airdata UAV')} Report",
                f"# Agency: {metadata.get('agency', '')}",
                f"# Report number: {metadata.get('report_number', '')}",
                f"# Period: {metadata.get('period_start', '')} to {metadata.get('period_end', '')}",
                f"# Reported flights: {metadata.get('total_flights', '')}",
                f"# Created: {metadata.get('created', '')}",
                f"# Filtered flights: {len(flights)}",
            ]
            fh.write('\r\n'.join(meta_lines) + '\r\n')

        writer = csv.DictWriter(fh, fieldnames=FIELDS, extrasaction='ignore',
                                dialect='excel', quoting=csv.QUOTE_ALL)
        writer.writeheader()
        for fl in flights:
            writer.writerow({k: clean(fl.get(k, '')) for k in FIELDS})


def write_xlsx(xlsx_path, metadata, flights):
    wb = Workbook()

    fs = wb.active
    fs.title = "Flights"
    header_fill = PatternFill("solid", fgColor="2F5496")
    header_font = Font(bold=True, color="FFFFFF")

    fs.append(FIELDS)
    for cell in fs[1]:
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal="center")
    fs.freeze_panes = "A2"

    for fl in flights:
        fs.append([clean(fl.get(k, '')) for k in FIELDS])

    for col_idx, field in enumerate(FIELDS, 1):
        col_letter = get_column_letter(col_idx)
        max_len = max(
            len(field),
            max((len(clean(fl.get(field, ''))) for fl in flights), default=0)
        )
        fs.column_dimensions[col_letter].width = min(max_len + 2, 60)

    ms = wb.create_sheet("Metadata")
    label_font = Font(bold=True)
    meta_rows = [
        ("Generated by",    metadata.get('generated_by', '')),
        ("Agency",          metadata.get('agency', '')),
        ("Report number",   metadata.get('report_number', '')),
        ("Period start",    metadata.get('period_start', '')),
        ("Period end",      metadata.get('period_end', '')),
        ("Reported flights",metadata.get('total_flights', '')),
        ("Created",         metadata.get('created', '')),
        ("Parsed flights",  str(len(flights))),
    ]
    for label, value in meta_rows:
        ms.append([label, value])
        ms.cell(ms.max_row, 1).font = label_font
    ms.column_dimensions['A'].width = 22
    ms.column_dimensions['B'].width = 50

    wb.save(xlsx_path)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    args = sys.argv[1:]
    include_metadata = '--comments' in args
    args = [a for a in args if a != '--comments']

    if not args:
        print(f"Usage: {sys.argv[0]} [--comments] <input.pdf> [output.csv]", file=sys.stderr)
        sys.exit(1)

    pdf_path = args[0]
    out_path = args[1] if len(args) > 1 else str(Path(pdf_path).with_suffix('.csv'))

    print("Extracting pages…")
    pages, total_pages, page_words, blue_rects = extract_pages(pdf_path)
    print(f"  {total_pages} pages")

    print("Parsing metadata…")
    meta = parse_metadata(pages, pdf_path)

    print("Parsing flights…")
    flights = parse_flights(pages, page_words, blue_rects)

    meta_display = [
        ("Generated by",    meta.get('generated_by', '')),
        ("Agency",          meta.get('agency', '')),
        ("Report number",   meta.get('report_number', '')),
        ("Period",          f"{meta.get('period_start','')} to {meta.get('period_end','')}"),
        ("Reported flights",meta.get('total_flights', '')),
        ("Created",         meta.get('created', '')),
        ("Parsed flights",  str(len(flights))),
    ]
    print()
    for label, value in meta_display:
        print(f"  {label + ':':20s} {value}".rstrip())
    print()

    write_csv(out_path, meta, flights, include_metadata)
    print(f"Written {out_path}")

    xlsx_path = str(Path(out_path).with_suffix('.xlsx'))
    write_xlsx(xlsx_path, meta, flights)
    print(f"Written {xlsx_path}")


if __name__ == '__main__':
    main()